### ISSUE TITLE
能不能整一个针对全局应用的

### ISSUE THREAD

**Issue by liangjinghao** [KitsunePie/BCRfullscreen#2]
能不能整一个针对全局应用的,

**Comment by keta1** [comment]
https://github.com/KitsunePie/BCRfullscreen/blob/827f79234898eecd0d74100ab454b9f984688ff8/app/src/main/java/com/ketal/bcrfullscreen/MainHook.java#L38
删了这行自己编译就有了

**Comment by liangjinghao** [comment]
> https://github.com/KitsunePie/BCRfullscreen/blob/827f79234898eecd0d74100ab454b9f984688ff8/app/src/main/java/com/ketal/bcrfullscreen/MainHook.java#L38
> 
> 
> 删了这行自己编译就有了

能做伸手党吗?没基础不会弄

**Comment by keta1** [comment]
[app-release.zip](https://github.com/KitsunePie/BCRfullscreen/files/7234300/app-release.zip)


> > https://github.com/KitsunePie/BCRfullscreen/blob/827f79234898eecd0d74100ab454b9f984688ff8/app/src/main/java/com/ketal/bcrfullscreen/MainHook.java#L38
> > 
> > 删了这行自己编译就有了
> 
> 能做伸手党吗?没基础不会弄

给

**Comment by liangjinghao** [comment]
> [app-release.zip](https://github.com/KitsunePie/BCRfullscreen/files/7234300/app-release.zip)
> 
> > > https://github.com/KitsunePie/BCRfullscreen/blob/827f79234898eecd0d74100ab454b9f984688ff8/app/src/main/java/com/ketal/bcrfullscreen/MainHook.java#L38
> > > 
> > > 删了这行自己编译就有了
> > 
> > 
> > 能做伸手党吗?没基础不会弄
> 
> 给

谢谢，但是并没有效果，只是把原来的黑边变成白边了好像，横屏的时候打孔位置还是有条边不能显示内容，有个magisk模块None Display Cutout，有不显示黑边的功能，但我手机mi10 pro上兼容不好，时间位置重叠，边角很多小锯齿
